---
- name: Resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
    force: true
- name: Resolv.conf remove
  ansible.builtin.file:
    path: "/etc/resolv.conf"
    state: absent
- name: Resolv.conf re-write
  ansible.builtin.blockinfile:
    path: "/etc/resolv.conf"
    create: true
    marker: "# {mark}"
    block: |
      nameserver 1.1.1.1
      domain {{ domain }}
      search {{ domain }}
