---
- name: Set ubuntu code name
  ansible.builtin.set_fact:
    ubuntu_codename: "{{ lookup('ini', 'UBUNTU_CODENAME type=properties file=' + ansible_distribution_file_path) }}"
- name: Nodejs repo key
  ansible.builtin.apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
    keyring: /usr/share/keyrings/nodesource.gpg
  become: true
  when: ansible_os_family == 'Debian'

- name: Nodejs repository remove nodesource.list
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/nodesource.list"
    state: absent
  when: ansible_os_family == 'Debian'

- name: Nodejs repository add nodesource
  ansible.builtin.apt_repository:
    validate_certs: false
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/nodesource.gpg] http://deb.nodesource.com/node_{{ node_version }}.x {{ ubuntu_codename }} main
    state: present
    filename: falsedesource
  when: ansible_os_family == 'Debian'

- name: Nodejs repository add nodesource
  ansible.builtin.apt_repository:
    validate_certs: false
    repo: deb-src [arch=amd64 signed-by=/usr/share/keyrings/nodesource.gpg] http://deb.nodesource.com/node_{{ node_version }}.x {{ ubuntu_codename }} main
    state: present
    filename: falsedesource
  when: ansible_os_family == 'Debian'

- name: Nodejs install
  ansible.builtin.apt:
    name:
      - nodejs
    state: present
  when: ansible_os_family == 'Debian'

- name: Npmrc
  ansible.builtin.template:
    src: npmrc
    dest: "{{ home }}/.npmrc"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Check bash installed
  ansible.builtin.stat:
    path: "/usr/bin/bash"
  register: stat_bash

- name: Cfg 20_js bash
  ansible.builtin.template:
    src: "20_js.cfg"
    dest: "{{ config }}/bash/20_js.cfg"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
  when: stat_bash.stat.exists

- name: Check zsh installed
  ansible.builtin.stat:
    path: "/usr/bin/zsh"
  register: stat_zsh

- name: Cfg 20_js zsh
  ansible.builtin.template:
    src: "20_js.cfg"
    dest: "{{ config }}/zsh/cfg/20_js.cfg"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
  when: stat_zsh.stat.exists
