---
- name: Smb.conf remove
  ansible.builtin.file:
    path: "/etc/samba/smb.conf"
    state: absent
- name: Smb.conf re-write
  ansible.builtin.blockinfile:
    path: "/etc/samba/smb.conf"
    create: true
    marker: "# {mark}"
    block: |
      [global]
      security = ADS
      workgroup = {{ ntdomain }}
      realm = {{ realm }}
      encrypt passwords = yes
      log file = /var/log/samba/%m.log
      log level = 1
      load printers = no
      vfs objects = acl_xattr
      map acl inherit = yes
      store dos attributes = yes
      acl allow execute always = yes
      inherit acls = yes
      inherit owner = yes
      inherit permissions = yes
      directory mask = 0775
      create mask = 0775
      idmap config * : backend = tdb
      idmap config * : range = 3000-7999
      idmap config {{ ntdomain }} : backend = rid
      idmap config {{ ntdomain }} : range 10000001-20000000
      ;[share]
      ;path = /share
      ;read only = no
