---
- name: copy templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { src: "dovecot.conf", dest: "/etc/dovecot/", mode: "0644" }
    - { src: "dovecot-sql.conf", dest: "/etc/dovecot/", mode: "0644" }
    - { src: "10-auth.conf", dest: "/etc/dovecot/conf.d/", mode: "0644" }
    - { src: "10-mail.conf", dest: "/etc/dovecot/conf.d/", mode: "0644" }
    - { src: "10-master.conf", dest: "/etc/dovecot/conf.d/", mode: "0644" }
    - { src: "10-ssl.conf", dest: "/etc/dovecot/conf.d/", mode: "0644" }